/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MenuAjout (void);
GtkWidget* create_MenuAgents (void);
GtkWidget* create_MenuModifier (void);
GtkWidget* create_MenuPrincipale (void);
GtkWidget* create_Menurechercher (void);
GtkWidget* create_MenuResrvation (void);
GtkWidget* create_MenuInformationPer (void);
GtkWidget* create_menuafrev (void);
