/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_MenuAjout (void)
{
  GtkWidget *MenuAjout;
  GtkWidget *fixed1;
  GtkObject *spinbuttonJourDepart_adj;
  GtkWidget *spinbuttonJourDepart;
  GtkObject *spinbuttonMois_adj;
  GtkWidget *spinbuttonMois;
  GtkObject *spinbuttonAnnee_adj;
  GtkWidget *spinbuttonAnnee;
  GtkObject *spinbuttonPrix_adj;
  GtkWidget *spinbuttonPrix;
  GtkWidget *label_2;
  GtkWidget *label_13;
  GtkWidget *labelMsg;
  GtkWidget *label_4;
  GtkWidget *label_3;
  GtkWidget *label_5;
  GtkWidget *comboboxDestination;
  GtkWidget *label_6;
  GtkWidget *label_8;
  GtkWidget *label_7;
  GtkWidget *comboboxDepart;
  GtkWidget *comboboxClass;
  GtkWidget *label_14;
  GtkWidget *buttonRetour;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label_16;
  GtkWidget *buttonAppliquer;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label_15;

  MenuAjout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (MenuAjout, 700, 500);
  gtk_window_set_title (GTK_WINDOW (MenuAjout), _("MenuAjout"));
  gtk_window_set_position (GTK_WINDOW (MenuAjout), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (MenuAjout), TRUE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (MenuAjout), fixed1);

  spinbuttonJourDepart_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonJourDepart = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJourDepart_adj), 1, 0);
  gtk_widget_show (spinbuttonJourDepart);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonJourDepart, 248, 200);
  gtk_widget_set_size_request (spinbuttonJourDepart, 56, 29);

  spinbuttonMois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonMois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMois_adj), 1, 0);
  gtk_widget_show (spinbuttonMois);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonMois, 368, 200);
  gtk_widget_set_size_request (spinbuttonMois, 56, 29);

  spinbuttonAnnee_adj = gtk_adjustment_new (2020, 2020, 2025, 1, 10, 10);
  spinbuttonAnnee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAnnee_adj), 1, 0);
  gtk_widget_show (spinbuttonAnnee);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonAnnee, 504, 200);
  gtk_widget_set_size_request (spinbuttonAnnee, 56, 29);

  spinbuttonPrix_adj = gtk_adjustment_new (100, 100, 3000, 1, 10, 10);
  spinbuttonPrix = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonPrix_adj), 1, 0);
  gtk_widget_show (spinbuttonPrix);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonPrix, 192, 280);
  gtk_widget_set_size_request (spinbuttonPrix, 56, 29);

  label_2 = gtk_label_new (_("Menu Ajout Vols"));
  gtk_widget_show (label_2);
  gtk_fixed_put (GTK_FIXED (fixed1), label_2, 296, 8);
  gtk_widget_set_size_request (label_2, 120, 35);

  label_13 = gtk_label_new (_("Prix"));
  gtk_widget_show (label_13);
  gtk_fixed_put (GTK_FIXED (fixed1), label_13, 128, 280);
  gtk_widget_set_size_request (label_13, 56, 32);

  labelMsg = gtk_label_new ("");
  gtk_widget_show (labelMsg);
  gtk_fixed_put (GTK_FIXED (fixed1), labelMsg, 128, 336);
  gtk_widget_set_size_request (labelMsg, 432, 64);

  label_4 = gtk_label_new (_("Depart"));
  gtk_widget_show (label_4);
  gtk_fixed_put (GTK_FIXED (fixed1), label_4, 152, 120);
  gtk_widget_set_size_request (label_4, 80, 32);

  label_3 = gtk_label_new (_("Destination"));
  gtk_widget_show (label_3);
  gtk_fixed_put (GTK_FIXED (fixed1), label_3, 144, 64);
  gtk_widget_set_size_request (label_3, 112, 35);

  label_5 = gtk_label_new (_("Date de Depart"));
  gtk_widget_show (label_5);
  gtk_fixed_put (GTK_FIXED (fixed1), label_5, 56, 200);
  gtk_widget_set_size_request (label_5, 120, 32);

  comboboxDestination = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxDestination);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxDestination, 296, 64);
  gtk_widget_set_size_request (comboboxDestination, 150, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Alg\303\251rie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Belgique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Canada"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Croatie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Danemark"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("\303\211tats-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Espagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Italie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Libye"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Luxembourg"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Maroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Pays Bas"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Portugal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Su\303\250de"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Tunisie"));

  label_6 = gtk_label_new (_("Jours"));
  gtk_widget_show (label_6);
  gtk_fixed_put (GTK_FIXED (fixed1), label_6, 184, 200);
  gtk_widget_set_size_request (label_6, 54, 32);
  gtk_misc_set_padding (GTK_MISC (label_6), 5, 0);

  label_8 = gtk_label_new (_("Annee"));
  gtk_widget_show (label_8);
  gtk_fixed_put (GTK_FIXED (fixed1), label_8, 424, 200);
  gtk_widget_set_size_request (label_8, 72, 32);

  label_7 = gtk_label_new (_("Mois"));
  gtk_widget_show (label_7);
  gtk_fixed_put (GTK_FIXED (fixed1), label_7, 312, 200);
  gtk_widget_set_size_request (label_7, 48, 32);

  comboboxDepart = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxDepart);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxDepart, 296, 120);
  gtk_widget_set_size_request (comboboxDepart, 150, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Alg\303\251rie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Belgique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Canada"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Croatie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Danemark"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("\303\211tats-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Espagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Italie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Libye"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Luxembourg"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Maroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Pays Bas"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Portugal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Su\303\250de"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Tunisie"));

  comboboxClass = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxClass);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxClass, 424, 280);
  gtk_widget_set_size_request (comboboxClass, 176, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClass), _("ClasseEconomique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClass), _("ClassePremium"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClass), _("ClasseAffaire"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClass), _("ClassePremi\303\250re"));

  label_14 = gtk_label_new (_("Classe"));
  gtk_widget_show (label_14);
  gtk_fixed_put (GTK_FIXED (fixed1), label_14, 336, 280);
  gtk_widget_set_size_request (label_14, 80, 32);

  buttonRetour = gtk_button_new ();
  gtk_widget_show (buttonRetour);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonRetour, 376, 424);
  gtk_widget_set_size_request (buttonRetour, 100, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonRetour), alignment2);
  gtk_widget_set_size_request (alignment2, 69, -1);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label_16 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label_16);
  gtk_box_pack_start (GTK_BOX (hbox2), label_16, FALSE, FALSE, 0);

  buttonAppliquer = gtk_button_new ();
  gtk_widget_show (buttonAppliquer);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAppliquer, 216, 424);
  gtk_widget_set_size_request (buttonAppliquer, 100, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonAppliquer), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label_15 = gtk_label_new_with_mnemonic (_("Appliquer"));
  gtk_widget_show (label_15);
  gtk_box_pack_start (GTK_BOX (hbox6), label_15, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonRetour, "clicked",
                    G_CALLBACK (on_buttonRetour_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAppliquer, "clicked",
                    G_CALLBACK (on_buttonAppliquer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MenuAjout, MenuAjout, "MenuAjout");
  GLADE_HOOKUP_OBJECT (MenuAjout, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (MenuAjout, spinbuttonJourDepart, "spinbuttonJourDepart");
  GLADE_HOOKUP_OBJECT (MenuAjout, spinbuttonMois, "spinbuttonMois");
  GLADE_HOOKUP_OBJECT (MenuAjout, spinbuttonAnnee, "spinbuttonAnnee");
  GLADE_HOOKUP_OBJECT (MenuAjout, spinbuttonPrix, "spinbuttonPrix");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_2, "label_2");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_13, "label_13");
  GLADE_HOOKUP_OBJECT (MenuAjout, labelMsg, "labelMsg");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_4, "label_4");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_3, "label_3");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_5, "label_5");
  GLADE_HOOKUP_OBJECT (MenuAjout, comboboxDestination, "comboboxDestination");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_6, "label_6");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_8, "label_8");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_7, "label_7");
  GLADE_HOOKUP_OBJECT (MenuAjout, comboboxDepart, "comboboxDepart");
  GLADE_HOOKUP_OBJECT (MenuAjout, comboboxClass, "comboboxClass");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_14, "label_14");
  GLADE_HOOKUP_OBJECT (MenuAjout, buttonRetour, "buttonRetour");
  GLADE_HOOKUP_OBJECT (MenuAjout, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (MenuAjout, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (MenuAjout, image2, "image2");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_16, "label_16");
  GLADE_HOOKUP_OBJECT (MenuAjout, buttonAppliquer, "buttonAppliquer");
  GLADE_HOOKUP_OBJECT (MenuAjout, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (MenuAjout, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (MenuAjout, image6, "image6");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_15, "label_15");

  return MenuAjout;
}

GtkWidget*
create_MenuAgents (void)
{
  GtkWidget *MenuAgents;
  GtkWidget *fixed2;
  GtkWidget *treeviewListeVols;
  GtkWidget *entrySelection;
  GtkWidget *labelNotification;
  GtkWidget *buttonAjouter;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label_22;
  GtkWidget *buttonSupprimerVols;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label_23;
  GtkWidget *buttonModifierVol;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label_21;
  GtkWidget *buttonRechercher;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label13;
  GtkWidget *image25;
  GtkWidget *buttonRetourP;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image23;
  GtkWidget *label42;
  GtkWidget *image24;
  GtkWidget *buttonAfficher;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label12;

  MenuAgents = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (MenuAgents, 700, 500);
  gtk_window_set_title (GTK_WINDOW (MenuAgents), _("MenuAgents"));
  gtk_window_set_position (GTK_WINDOW (MenuAgents), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (MenuAgents), TRUE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (MenuAgents), fixed2);

  treeviewListeVols = gtk_tree_view_new ();
  gtk_widget_show (treeviewListeVols);
  gtk_fixed_put (GTK_FIXED (fixed2), treeviewListeVols, 0, 208);
  gtk_widget_set_size_request (treeviewListeVols, 592, 160);

  entrySelection = gtk_entry_new ();
  gtk_widget_show (entrySelection);
  gtk_fixed_put (GTK_FIXED (fixed2), entrySelection, 96, 8);
  gtk_widget_set_size_request (entrySelection, 496, 39);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrySelection), 8226);

  labelNotification = gtk_label_new ("");
  gtk_widget_show (labelNotification);
  gtk_fixed_put (GTK_FIXED (fixed2), labelNotification, 40, 400);
  gtk_widget_set_size_request (labelNotification, 216, 48);

  buttonAjouter = gtk_button_new ();
  gtk_widget_show (buttonAjouter);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAjouter, 592, 248);
  gtk_widget_set_size_request (buttonAjouter, 104, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonAjouter), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label_22 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label_22);
  gtk_box_pack_start (GTK_BOX (hbox5), label_22, FALSE, FALSE, 0);

  buttonSupprimerVols = gtk_button_new ();
  gtk_widget_show (buttonSupprimerVols);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonSupprimerVols, 592, 288);
  gtk_widget_set_size_request (buttonSupprimerVols, 104, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonSupprimerVols), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label_23 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label_23);
  gtk_box_pack_start (GTK_BOX (hbox3), label_23, FALSE, FALSE, 0);

  buttonModifierVol = gtk_button_new ();
  gtk_widget_show (buttonModifierVol);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonModifierVol, 592, 328);
  gtk_widget_set_size_request (buttonModifierVol, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonModifierVol), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label_21 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label_21);
  gtk_box_pack_start (GTK_BOX (hbox4), label_21, FALSE, FALSE, 0);

  buttonRechercher = gtk_button_new ();
  gtk_widget_show (buttonRechercher);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonRechercher, 592, 8);
  gtk_widget_set_size_request (buttonRechercher, 104, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonRechercher), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Rechercher "));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox10), label13, FALSE, FALSE, 0);

  image25 = create_pixmap (MenuAgents, "113.png");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed2), image25, 0, 368);
  gtk_widget_set_size_request (image25, 696, 120);

  buttonRetourP = gtk_button_new ();
  gtk_widget_show (buttonRetourP);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonRetourP, 0, 8);
  gtk_widget_set_size_request (buttonRetourP, 96, 40);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (buttonRetourP), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image23 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox22), image23, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox22), label42, FALSE, FALSE, 0);

  image24 = create_pixmap (MenuAgents, "45.jpg");
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed2), image24, 0, 48);
  gtk_widget_set_size_request (image24, 696, 160);

  buttonAfficher = gtk_button_new ();
  gtk_widget_show (buttonAfficher);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAfficher, 592, 208);
  gtk_widget_set_size_request (buttonAfficher, 104, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonAfficher), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox9), label12, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonAjouter, "clicked",
                    G_CALLBACK (on_buttonAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupprimerVols, "clicked",
                    G_CALLBACK (on_buttonSupprimerVols_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifierVol, "clicked",
                    G_CALLBACK (on_buttonModifierVol_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRechercher, "clicked",
                    G_CALLBACK (on_buttonRechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRetourP, "clicked",
                    G_CALLBACK (on_buttonRetourP_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAfficher, "clicked",
                    G_CALLBACK (on_buttonAfficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MenuAgents, MenuAgents, "MenuAgents");
  GLADE_HOOKUP_OBJECT (MenuAgents, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (MenuAgents, treeviewListeVols, "treeviewListeVols");
  GLADE_HOOKUP_OBJECT (MenuAgents, entrySelection, "entrySelection");
  GLADE_HOOKUP_OBJECT (MenuAgents, labelNotification, "labelNotification");
  GLADE_HOOKUP_OBJECT (MenuAgents, buttonAjouter, "buttonAjouter");
  GLADE_HOOKUP_OBJECT (MenuAgents, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (MenuAgents, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (MenuAgents, image5, "image5");
  GLADE_HOOKUP_OBJECT (MenuAgents, label_22, "label_22");
  GLADE_HOOKUP_OBJECT (MenuAgents, buttonSupprimerVols, "buttonSupprimerVols");
  GLADE_HOOKUP_OBJECT (MenuAgents, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (MenuAgents, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (MenuAgents, image3, "image3");
  GLADE_HOOKUP_OBJECT (MenuAgents, label_23, "label_23");
  GLADE_HOOKUP_OBJECT (MenuAgents, buttonModifierVol, "buttonModifierVol");
  GLADE_HOOKUP_OBJECT (MenuAgents, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (MenuAgents, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (MenuAgents, image4, "image4");
  GLADE_HOOKUP_OBJECT (MenuAgents, label_21, "label_21");
  GLADE_HOOKUP_OBJECT (MenuAgents, buttonRechercher, "buttonRechercher");
  GLADE_HOOKUP_OBJECT (MenuAgents, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (MenuAgents, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (MenuAgents, image10, "image10");
  GLADE_HOOKUP_OBJECT (MenuAgents, label13, "label13");
  GLADE_HOOKUP_OBJECT (MenuAgents, image25, "image25");
  GLADE_HOOKUP_OBJECT (MenuAgents, buttonRetourP, "buttonRetourP");
  GLADE_HOOKUP_OBJECT (MenuAgents, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (MenuAgents, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (MenuAgents, image23, "image23");
  GLADE_HOOKUP_OBJECT (MenuAgents, label42, "label42");
  GLADE_HOOKUP_OBJECT (MenuAgents, image24, "image24");
  GLADE_HOOKUP_OBJECT (MenuAgents, buttonAfficher, "buttonAfficher");
  GLADE_HOOKUP_OBJECT (MenuAgents, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (MenuAgents, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (MenuAgents, image9, "image9");
  GLADE_HOOKUP_OBJECT (MenuAgents, label12, "label12");

  return MenuAgents;
}

GtkWidget*
create_MenuModifier (void)
{
  GtkWidget *MenuModifier;
  GtkWidget *fixed3;
  GtkObject *spinbuttonJoursM_adj;
  GtkWidget *spinbuttonJoursM;
  GtkObject *spinbuttonMoisM_adj;
  GtkWidget *spinbuttonMoisM;
  GtkObject *spinbuttonAnneeM_adj;
  GtkWidget *spinbuttonAnneeM;
  GtkWidget *labelIdAModifier;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *buttonRetourN;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label10;
  GtkWidget *labelAncienPrix;
  GtkWidget *buttonAfficheAncien;
  GtkWidget *comboboxDepartM;
  GtkWidget *comboboxDestinationM;
  GtkWidget *labelAncienDepart;
  GtkWidget *labelAncienDestination;
  GtkWidget *labelAncienDate;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *labelAncienClass;
  GtkWidget *labelJourM;
  GtkWidget *labelMoisM;
  GtkWidget *labelAnneeM;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *labelPrixM;
  GtkWidget *comboboxClassM;
  GtkWidget *labelMsgM;
  GtkWidget *buttonModifierN;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label11;

  MenuModifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (MenuModifier, 700, 500);
  gtk_window_set_title (GTK_WINDOW (MenuModifier), _("MenuModifier"));
  gtk_window_set_position (GTK_WINDOW (MenuModifier), GTK_WIN_POS_CENTER);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (MenuModifier), fixed3);
  gtk_widget_set_size_request (fixed3, 756, 628);

  spinbuttonJoursM_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonJoursM = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJoursM_adj), 1, 0);
  gtk_widget_show (spinbuttonJoursM);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonJoursM, 272, 200);
  gtk_widget_set_size_request (spinbuttonJoursM, 48, 25);

  spinbuttonMoisM_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonMoisM = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMoisM_adj), 1, 0);
  gtk_widget_show (spinbuttonMoisM);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonMoisM, 368, 200);
  gtk_widget_set_size_request (spinbuttonMoisM, 48, 24);

  spinbuttonAnneeM_adj = gtk_adjustment_new (2020, 2020, 2025, 1, 10, 10);
  spinbuttonAnneeM = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAnneeM_adj), 1, 0);
  gtk_widget_show (spinbuttonAnneeM);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonAnneeM, 472, 200);
  gtk_widget_set_size_request (spinbuttonAnneeM, 57, 24);

  labelIdAModifier = gtk_label_new ("");
  gtk_widget_show (labelIdAModifier);
  gtk_fixed_put (GTK_FIXED (fixed3), labelIdAModifier, 248, 8);
  gtk_widget_set_size_request (labelIdAModifier, 200, 35);

  spinbutton1_adj = gtk_adjustment_new (100, 100, 3000, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1, 256, 288);
  gtk_widget_set_size_request (spinbutton1, 64, 24);

  buttonRetourN = gtk_button_new ();
  gtk_widget_show (buttonRetourN);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonRetourN, 488, 440);
  gtk_widget_set_size_request (buttonRetourN, 96, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonRetourN), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox7), label10, FALSE, FALSE, 0);

  labelAncienPrix = gtk_label_new ("");
  gtk_widget_show (labelAncienPrix);
  gtk_fixed_put (GTK_FIXED (fixed3), labelAncienPrix, 208, 280);
  gtk_widget_set_size_request (labelAncienPrix, 168, 32);

  buttonAfficheAncien = gtk_button_new_with_mnemonic (_("Afficher "));
  gtk_widget_show (buttonAfficheAncien);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonAfficheAncien, 112, 440);
  gtk_widget_set_size_request (buttonAfficheAncien, 104, 40);

  comboboxDepartM = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxDepartM);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxDepartM, 248, 64);
  gtk_widget_set_size_request (comboboxDepartM, 180, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Alg\303\251rie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Belgique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Canada"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Croatie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Danemark"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("\303\211tats-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Espagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Italie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Libye"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Luxembourg"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Maroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Pays Bas"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Portugal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Su\303\250de"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Tunisie"));

  comboboxDestinationM = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxDestinationM);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxDestinationM, 248, 112);
  gtk_widget_set_size_request (comboboxDestinationM, 180, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Alg\303\251rie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Belgique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Canada"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Croatie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Danemark"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("\303\211tats-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Espagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Italie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Libye"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Luxembourg"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Maroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Pays Bas"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Portugal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Su\303\250de"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Tunisie"));

  labelAncienDepart = gtk_label_new ("");
  gtk_widget_show (labelAncienDepart);
  gtk_fixed_put (GTK_FIXED (fixed3), labelAncienDepart, 440, 64);
  gtk_widget_set_size_request (labelAncienDepart, 240, 32);

  labelAncienDestination = gtk_label_new ("");
  gtk_widget_show (labelAncienDestination);
  gtk_fixed_put (GTK_FIXED (fixed3), labelAncienDestination, 440, 104);
  gtk_widget_set_size_request (labelAncienDestination, 224, 40);

  labelAncienDate = gtk_label_new ("");
  gtk_widget_show (labelAncienDate);
  gtk_fixed_put (GTK_FIXED (fixed3), labelAncienDate, 456, 160);
  gtk_widget_set_size_request (labelAncienDate, 216, 32);

  label43 = gtk_label_new (_("Depart :"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed3), label43, 160, 72);
  gtk_widget_set_size_request (label43, 72, 19);

  label44 = gtk_label_new (_("Destination :"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed3), label44, 136, 112);
  gtk_widget_set_size_request (label44, 93, 27);

  labelAncienClass = gtk_label_new ("");
  gtk_widget_show (labelAncienClass);
  gtk_fixed_put (GTK_FIXED (fixed3), labelAncienClass, 464, 336);
  gtk_widget_set_size_request (labelAncienClass, 232, 40);

  labelJourM = gtk_label_new (_("Jour"));
  gtk_widget_show (labelJourM);
  gtk_fixed_put (GTK_FIXED (fixed3), labelJourM, 224, 200);
  gtk_widget_set_size_request (labelJourM, 56, 24);

  labelMoisM = gtk_label_new (_("Mois"));
  gtk_widget_show (labelMoisM);
  gtk_fixed_put (GTK_FIXED (fixed3), labelMoisM, 320, 200);
  gtk_widget_set_size_request (labelMoisM, 56, 24);

  labelAnneeM = gtk_label_new (_("Annee"));
  gtk_widget_show (labelAnneeM);
  gtk_fixed_put (GTK_FIXED (fixed3), labelAnneeM, 424, 208);
  gtk_widget_set_size_request (labelAnneeM, 45, 20);

  label45 = gtk_label_new (_("Date de depart :"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed3), label45, 112, 160);
  gtk_widget_set_size_request (label45, 117, 27);

  label46 = gtk_label_new (_("Classe :"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed3), label46, 184, 232);
  gtk_widget_set_size_request (label46, 45, 19);

  labelPrixM = gtk_label_new (_("Prix"));
  gtk_widget_show (labelPrixM);
  gtk_fixed_put (GTK_FIXED (fixed3), labelPrixM, 176, 288);
  gtk_widget_set_size_request (labelPrixM, 64, 27);

  comboboxClassM = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxClassM);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxClassM, 248, 240);
  gtk_widget_set_size_request (comboboxClassM, 180, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClassM), _("ClasseEconomique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClassM), _("ClassePremium"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClassM), _("ClasseAffaire"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClassM), _("ClassePremi\303\250re"));

  labelMsgM = gtk_label_new ("");
  gtk_widget_show (labelMsgM);
  gtk_fixed_put (GTK_FIXED (fixed3), labelMsgM, 144, 344);
  gtk_widget_set_size_request (labelMsgM, 424, 64);

  buttonModifierN = gtk_button_new ();
  gtk_widget_show (buttonModifierN);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonModifierN, 272, 440);
  gtk_widget_set_size_request (buttonModifierN, 96, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonModifierN), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Appliquer"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox8), label11, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonRetourN, "clicked",
                    G_CALLBACK (on_buttonRetourN_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAfficheAncien, "clicked",
                    G_CALLBACK (on_buttonAfficheAncien_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifierN, "clicked",
                    G_CALLBACK (on_buttonModifierN_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MenuModifier, MenuModifier, "MenuModifier");
  GLADE_HOOKUP_OBJECT (MenuModifier, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (MenuModifier, spinbuttonJoursM, "spinbuttonJoursM");
  GLADE_HOOKUP_OBJECT (MenuModifier, spinbuttonMoisM, "spinbuttonMoisM");
  GLADE_HOOKUP_OBJECT (MenuModifier, spinbuttonAnneeM, "spinbuttonAnneeM");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelIdAModifier, "labelIdAModifier");
  GLADE_HOOKUP_OBJECT (MenuModifier, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (MenuModifier, buttonRetourN, "buttonRetourN");
  GLADE_HOOKUP_OBJECT (MenuModifier, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (MenuModifier, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (MenuModifier, image7, "image7");
  GLADE_HOOKUP_OBJECT (MenuModifier, label10, "label10");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelAncienPrix, "labelAncienPrix");
  GLADE_HOOKUP_OBJECT (MenuModifier, buttonAfficheAncien, "buttonAfficheAncien");
  GLADE_HOOKUP_OBJECT (MenuModifier, comboboxDepartM, "comboboxDepartM");
  GLADE_HOOKUP_OBJECT (MenuModifier, comboboxDestinationM, "comboboxDestinationM");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelAncienDepart, "labelAncienDepart");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelAncienDestination, "labelAncienDestination");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelAncienDate, "labelAncienDate");
  GLADE_HOOKUP_OBJECT (MenuModifier, label43, "label43");
  GLADE_HOOKUP_OBJECT (MenuModifier, label44, "label44");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelAncienClass, "labelAncienClass");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelJourM, "labelJourM");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelMoisM, "labelMoisM");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelAnneeM, "labelAnneeM");
  GLADE_HOOKUP_OBJECT (MenuModifier, label45, "label45");
  GLADE_HOOKUP_OBJECT (MenuModifier, label46, "label46");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelPrixM, "labelPrixM");
  GLADE_HOOKUP_OBJECT (MenuModifier, comboboxClassM, "comboboxClassM");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelMsgM, "labelMsgM");
  GLADE_HOOKUP_OBJECT (MenuModifier, buttonModifierN, "buttonModifierN");
  GLADE_HOOKUP_OBJECT (MenuModifier, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (MenuModifier, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (MenuModifier, image8, "image8");
  GLADE_HOOKUP_OBJECT (MenuModifier, label11, "label11");

  return MenuModifier;
}

GtkWidget*
create_MenuPrincipale (void)
{
  GtkWidget *MenuPrincipale;
  GtkWidget *fixed4;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *button1;
  GtkWidget *image22;
  GtkWidget *buttonGestionVols;
  GtkWidget *buttonReservationVols;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *label41;
  GtkWidget *button4;

  MenuPrincipale = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (MenuPrincipale, 700, 500);
  gtk_window_set_title (GTK_WINDOW (MenuPrincipale), _("MenuPrincipale"));
  gtk_window_set_position (GTK_WINDOW (MenuPrincipale), GTK_WIN_POS_CENTER);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (MenuPrincipale), fixed4);

  button2 = gtk_button_new_with_mnemonic (_("Reservation excursion"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed4), button2, 184, 432);
  gtk_widget_set_size_request (button2, 152, 56);

  button3 = gtk_button_new_with_mnemonic (_("Reservation hotel"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed4), button3, 352, 432);
  gtk_widget_set_size_request (button3, 136, 56);

  button1 = gtk_button_new_with_mnemonic (_("Reservation voiture"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed4), button1, 352, 368);
  gtk_widget_set_size_request (button1, 136, 56);

  image22 = create_pixmap (MenuPrincipale, "45.jpg");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed4), image22, 0, 0);
  gtk_widget_set_size_request (image22, 696, 360);

  buttonGestionVols = gtk_button_new_with_mnemonic (_("VOLS"));
  gtk_widget_show (buttonGestionVols);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonGestionVols, 32, 368);
  gtk_widget_set_size_request (buttonGestionVols, 152, 56);

  buttonReservationVols = gtk_button_new ();
  gtk_widget_show (buttonReservationVols);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonReservationVols, 184, 368);
  gtk_widget_set_size_request (buttonReservationVols, 152, 56);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (buttonReservationVols), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  label41 = gtk_label_new_with_mnemonic (_("Reservervol"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox21), label41, FALSE, FALSE, 0);

  button4 = gtk_button_new_with_mnemonic (_("Reservation vol"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed4), button4, 32, 432);
  gtk_widget_set_size_request (button4, 152, 56);

  g_signal_connect ((gpointer) buttonGestionVols, "clicked",
                    G_CALLBACK (on_buttonGestionVols_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonReservationVols, "clicked",
                    G_CALLBACK (on_buttonReservationVols_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MenuPrincipale, MenuPrincipale, "MenuPrincipale");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, button2, "button2");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, button3, "button3");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, button1, "button1");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, image22, "image22");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, buttonGestionVols, "buttonGestionVols");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, buttonReservationVols, "buttonReservationVols");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, label41, "label41");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, button4, "button4");

  return MenuPrincipale;
}

GtkWidget*
create_Menurechercher (void)
{
  GtkWidget *Menurechercher;
  GtkWidget *fixed5;
  GtkWidget *treeview1;
  GtkWidget *entryRecherche;
  GtkWidget *labelMsgerr;
  GtkWidget *buttonRetourT;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label26;
  GtkWidget *comboboxRecherche;
  GtkWidget *buttonValidRecher;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label25;
  GtkWidget *buttonSuppRech;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image20;
  GtkWidget *label39;
  GtkWidget *buttonModifierRech;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image21;
  GtkWidget *label40;
  GtkWidget *buttonRefreche;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label27;

  Menurechercher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Menurechercher, 700, 500);
  gtk_window_set_title (GTK_WINDOW (Menurechercher), _("Menurechercher"));
  gtk_window_set_position (GTK_WINDOW (Menurechercher), GTK_WIN_POS_CENTER);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Menurechercher), fixed5);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview1, 0, 112);
  gtk_widget_set_size_request (treeview1, 592, 288);

  entryRecherche = gtk_entry_new ();
  gtk_widget_show (entryRecherche);
  gtk_fixed_put (GTK_FIXED (fixed5), entryRecherche, 200, 32);
  gtk_widget_set_size_request (entryRecherche, 392, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryRecherche), 8226);

  labelMsgerr = gtk_label_new ("");
  gtk_widget_show (labelMsgerr);
  gtk_fixed_put (GTK_FIXED (fixed5), labelMsgerr, 192, 432);
  gtk_widget_set_size_request (labelMsgerr, 312, 56);

  buttonRetourT = gtk_button_new ();
  gtk_widget_show (buttonRetourT);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonRetourT, 0, 24);
  gtk_widget_set_size_request (buttonRetourT, 100, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonRetourT), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox12), label26, FALSE, FALSE, 0);

  comboboxRecherche = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxRecherche);
  gtk_fixed_put (GTK_FIXED (fixed5), comboboxRecherche, 96, 24);
  gtk_widget_set_size_request (comboboxRecherche, 104, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxRecherche), _("Destination "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxRecherche), _("Depart"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxRecherche), _("Prix"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxRecherche), _("IdVols"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxRecherche), _("Classe"));

  buttonValidRecher = gtk_button_new ();
  gtk_widget_show (buttonValidRecher);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonValidRecher, 592, 32);
  gtk_widget_set_size_request (buttonValidRecher, 104, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttonValidRecher), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox11), label25, FALSE, FALSE, 0);

  buttonSuppRech = gtk_button_new ();
  gtk_widget_show (buttonSuppRech);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonSuppRech, 592, 152);
  gtk_widget_set_size_request (buttonSuppRech, 104, 40);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonSuppRech), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image20 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox19), image20, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox19), label39, FALSE, FALSE, 0);

  buttonModifierRech = gtk_button_new ();
  gtk_widget_show (buttonModifierRech);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonModifierRech, 592, 104);
  gtk_widget_set_size_request (buttonModifierRech, 112, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (buttonModifierRech), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image21 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox20), image21, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox20), label40, FALSE, FALSE, 0);

  buttonRefreche = gtk_button_new ();
  gtk_widget_show (buttonRefreche);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonRefreche, 592, 200);
  gtk_widget_set_size_request (buttonRefreche, 100, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttonRefreche), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox13), label27, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonRetourT, "clicked",
                    G_CALLBACK (on_buttonRetourT_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonValidRecher, "clicked",
                    G_CALLBACK (on_buttonValidRecher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSuppRech, "clicked",
                    G_CALLBACK (on_buttonSuppRech_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifierRech, "clicked",
                    G_CALLBACK (on_buttonModifierRech_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRefreche, "clicked",
                    G_CALLBACK (on_buttonRefreche_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Menurechercher, Menurechercher, "Menurechercher");
  GLADE_HOOKUP_OBJECT (Menurechercher, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Menurechercher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Menurechercher, entryRecherche, "entryRecherche");
  GLADE_HOOKUP_OBJECT (Menurechercher, labelMsgerr, "labelMsgerr");
  GLADE_HOOKUP_OBJECT (Menurechercher, buttonRetourT, "buttonRetourT");
  GLADE_HOOKUP_OBJECT (Menurechercher, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Menurechercher, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Menurechercher, image12, "image12");
  GLADE_HOOKUP_OBJECT (Menurechercher, label26, "label26");
  GLADE_HOOKUP_OBJECT (Menurechercher, comboboxRecherche, "comboboxRecherche");
  GLADE_HOOKUP_OBJECT (Menurechercher, buttonValidRecher, "buttonValidRecher");
  GLADE_HOOKUP_OBJECT (Menurechercher, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Menurechercher, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Menurechercher, image11, "image11");
  GLADE_HOOKUP_OBJECT (Menurechercher, label25, "label25");
  GLADE_HOOKUP_OBJECT (Menurechercher, buttonSuppRech, "buttonSuppRech");
  GLADE_HOOKUP_OBJECT (Menurechercher, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Menurechercher, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Menurechercher, image20, "image20");
  GLADE_HOOKUP_OBJECT (Menurechercher, label39, "label39");
  GLADE_HOOKUP_OBJECT (Menurechercher, buttonModifierRech, "buttonModifierRech");
  GLADE_HOOKUP_OBJECT (Menurechercher, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Menurechercher, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (Menurechercher, image21, "image21");
  GLADE_HOOKUP_OBJECT (Menurechercher, label40, "label40");
  GLADE_HOOKUP_OBJECT (Menurechercher, buttonRefreche, "buttonRefreche");
  GLADE_HOOKUP_OBJECT (Menurechercher, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Menurechercher, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Menurechercher, image13, "image13");
  GLADE_HOOKUP_OBJECT (Menurechercher, label27, "label27");

  return Menurechercher;
}

GtkWidget*
create_MenuResrvation (void)
{
  GtkWidget *MenuResrvation;
  GtkWidget *fixed6;
  GtkWidget *treeviewReserver;
  GtkWidget *entryRecherche;
  GtkWidget *buttonRetourMP;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label29;
  GtkWidget *comboboxChoix;
  GtkWidget *buttonRecherche;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label28;
  GtkWidget *buttonActualiser2;
  GtkWidget *image19;
  GtkWidget *buttonReserver;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label30;
  GtkWidget *buttonAfficherVol2;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label32;
  GtkWidget *labelMSG;

  MenuResrvation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (MenuResrvation, 700, 500);
  gtk_window_set_title (GTK_WINDOW (MenuResrvation), _("MenuResrvation"));
  gtk_window_set_position (GTK_WINDOW (MenuResrvation), GTK_WIN_POS_CENTER);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (MenuResrvation), fixed6);

  treeviewReserver = gtk_tree_view_new ();
  gtk_widget_show (treeviewReserver);
  gtk_fixed_put (GTK_FIXED (fixed6), treeviewReserver, 32, 120);
  gtk_widget_set_size_request (treeviewReserver, 648, 320);

  entryRecherche = gtk_entry_new ();
  gtk_widget_show (entryRecherche);
  gtk_fixed_put (GTK_FIXED (fixed6), entryRecherche, 224, 8);
  gtk_widget_set_size_request (entryRecherche, 336, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryRecherche), 8226);

  buttonRetourMP = gtk_button_new ();
  gtk_widget_show (buttonRetourMP);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonRetourMP, 8, 8);
  gtk_widget_set_size_request (buttonRetourMP, 100, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (buttonRetourMP), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox15), label29, FALSE, FALSE, 0);

  comboboxChoix = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxChoix);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxChoix, 104, 8);
  gtk_widget_set_size_request (comboboxChoix, 120, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxChoix), _("Destination "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxChoix), _("Depart"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxChoix), _("Prix"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxChoix), _("IdVols"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxChoix), _("Classe"));

  buttonRecherche = gtk_button_new ();
  gtk_widget_show (buttonRecherche);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonRecherche, 560, 8);
  gtk_widget_set_size_request (buttonRecherche, 112, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttonRecherche), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox14), label28, FALSE, FALSE, 0);

  buttonActualiser2 = gtk_button_new ();
  gtk_widget_show (buttonActualiser2);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonActualiser2, 624, 336);
  gtk_widget_set_size_request (buttonActualiser2, 40, 33);

  image19 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_container_add (GTK_CONTAINER (buttonActualiser2), image19);

  buttonReserver = gtk_button_new ();
  gtk_widget_show (buttonReserver);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonReserver, 568, 64);
  gtk_widget_set_size_request (buttonReserver, 112, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (buttonReserver), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-go-up", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox16), label30, FALSE, FALSE, 0);

  buttonAfficherVol2 = gtk_button_new ();
  gtk_widget_show (buttonAfficherVol2);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonAfficherVol2, 64, 80);
  gtk_widget_set_size_request (buttonAfficherVol2, 104, 40);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonAfficherVol2), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-zoom-100", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Consulter"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox18), label32, FALSE, FALSE, 0);

  labelMSG = gtk_label_new ("");
  gtk_widget_show (labelMSG);
  gtk_fixed_put (GTK_FIXED (fixed6), labelMSG, 96, 448);
  gtk_widget_set_size_request (labelMSG, 384, 40);

  g_signal_connect ((gpointer) buttonRetourMP, "clicked",
                    G_CALLBACK (on_buttonRetourMP_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRecherche, "clicked",
                    G_CALLBACK (on_buttonRecherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonActualiser2, "clicked",
                    G_CALLBACK (on_buttonActualiser2_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonReserver, "clicked",
                    G_CALLBACK (on_buttonReserver_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAfficherVol2, "clicked",
                    G_CALLBACK (on_buttonAfficherVol2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MenuResrvation, MenuResrvation, "MenuResrvation");
  GLADE_HOOKUP_OBJECT (MenuResrvation, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (MenuResrvation, treeviewReserver, "treeviewReserver");
  GLADE_HOOKUP_OBJECT (MenuResrvation, entryRecherche, "entryRecherche");
  GLADE_HOOKUP_OBJECT (MenuResrvation, buttonRetourMP, "buttonRetourMP");
  GLADE_HOOKUP_OBJECT (MenuResrvation, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (MenuResrvation, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (MenuResrvation, image15, "image15");
  GLADE_HOOKUP_OBJECT (MenuResrvation, label29, "label29");
  GLADE_HOOKUP_OBJECT (MenuResrvation, comboboxChoix, "comboboxChoix");
  GLADE_HOOKUP_OBJECT (MenuResrvation, buttonRecherche, "buttonRecherche");
  GLADE_HOOKUP_OBJECT (MenuResrvation, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (MenuResrvation, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (MenuResrvation, image14, "image14");
  GLADE_HOOKUP_OBJECT (MenuResrvation, label28, "label28");
  GLADE_HOOKUP_OBJECT (MenuResrvation, buttonActualiser2, "buttonActualiser2");
  GLADE_HOOKUP_OBJECT (MenuResrvation, image19, "image19");
  GLADE_HOOKUP_OBJECT (MenuResrvation, buttonReserver, "buttonReserver");
  GLADE_HOOKUP_OBJECT (MenuResrvation, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (MenuResrvation, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (MenuResrvation, image16, "image16");
  GLADE_HOOKUP_OBJECT (MenuResrvation, label30, "label30");
  GLADE_HOOKUP_OBJECT (MenuResrvation, buttonAfficherVol2, "buttonAfficherVol2");
  GLADE_HOOKUP_OBJECT (MenuResrvation, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (MenuResrvation, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (MenuResrvation, image18, "image18");
  GLADE_HOOKUP_OBJECT (MenuResrvation, label32, "label32");
  GLADE_HOOKUP_OBJECT (MenuResrvation, labelMSG, "labelMSG");

  return MenuResrvation;
}

GtkWidget*
create_MenuInformationPer (void)
{
  GtkWidget *MenuInformationPer;
  GtkWidget *fixed7;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label37;
  GtkWidget *buttonValiderRes;
  GtkWidget *buttonRetourRes;
  GtkWidget *label38;
  GtkWidget *label33;

  MenuInformationPer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (MenuInformationPer, 700, 500);
  gtk_window_set_title (GTK_WINDOW (MenuInformationPer), _("MenuInformationPer"));
  gtk_window_set_position (GTK_WINDOW (MenuInformationPer), GTK_WIN_POS_CENTER);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (MenuInformationPer), fixed7);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed7), entry1, 296, 72);
  gtk_widget_set_size_request (entry1, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed7), entry2, 296, 128);
  gtk_widget_set_size_request (entry2, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed7), entry3, 296, 184);
  gtk_widget_set_size_request (entry3, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label34 = gtk_label_new (_("CIN"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed7), label34, 160, 72);
  gtk_widget_set_size_request (label34, 96, 32);

  label35 = gtk_label_new (_("Nom "));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed7), label35, 160, 128);
  gtk_widget_set_size_request (label35, 104, 32);

  label37 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed7), label37, 144, 184);
  gtk_widget_set_size_request (label37, 136, 32);

  buttonValiderRes = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (buttonValiderRes);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonValiderRes, 176, 256);
  gtk_widget_set_size_request (buttonValiderRes, 152, 48);

  buttonRetourRes = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (buttonRetourRes);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonRetourRes, 384, 256);
  gtk_widget_set_size_request (buttonRetourRes, 152, 48);

  label38 = gtk_label_new ("");
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed7), label38, 120, 320);
  gtk_widget_set_size_request (label38, 472, 104);

  label33 = gtk_label_new (_("<b><span foreground=\"#1d4457\"size=\"xx-large\"\nweight=\"heavy\">INFORMATION DU CLIENT </span></b>"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed7), label33, 96, 16);
  gtk_widget_set_size_request (label33, 512, 48);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  g_signal_connect ((gpointer) buttonValiderRes, "clicked",
                    G_CALLBACK (on_buttonValiderRes_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRetourRes, "clicked",
                    G_CALLBACK (on_buttonRetourRes_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MenuInformationPer, MenuInformationPer, "MenuInformationPer");
  GLADE_HOOKUP_OBJECT (MenuInformationPer, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (MenuInformationPer, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (MenuInformationPer, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (MenuInformationPer, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (MenuInformationPer, label34, "label34");
  GLADE_HOOKUP_OBJECT (MenuInformationPer, label35, "label35");
  GLADE_HOOKUP_OBJECT (MenuInformationPer, label37, "label37");
  GLADE_HOOKUP_OBJECT (MenuInformationPer, buttonValiderRes, "buttonValiderRes");
  GLADE_HOOKUP_OBJECT (MenuInformationPer, buttonRetourRes, "buttonRetourRes");
  GLADE_HOOKUP_OBJECT (MenuInformationPer, label38, "label38");
  GLADE_HOOKUP_OBJECT (MenuInformationPer, label33, "label33");

  return MenuInformationPer;
}

GtkWidget*
create_menuafrev (void)
{
  GtkWidget *menuafrev;
  GtkWidget *fixed8;
  GtkWidget *entry4;
  GtkWidget *treeview2;
  GtkWidget *retourafres;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image27;
  GtkWidget *label48;
  GtkWidget *image28;
  GtkWidget *button5;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image26;
  GtkWidget *label47;
  GtkWidget *afficherlesreservation;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image29;
  GtkWidget *label49;

  menuafrev = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (menuafrev), _("menuafrev"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (menuafrev), fixed8);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed8), entry4, 96, 8);
  gtk_widget_set_size_request (entry4, 568, 39);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview2, 0, 208);
  gtk_widget_set_size_request (treeview2, 768, 184);

  retourafres = gtk_button_new ();
  gtk_widget_show (retourafres);
  gtk_fixed_put (GTK_FIXED (fixed8), retourafres, 0, 8);
  gtk_widget_set_size_request (retourafres, 96, 40);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (retourafres), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image27 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox24), image27, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox24), label48, FALSE, FALSE, 0);

  image28 = create_pixmap (menuafrev, "45.jpg");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed8), image28, 0, 48);
  gtk_widget_set_size_request (image28, 768, 160);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed8), button5, 664, 8);
  gtk_widget_set_size_request (button5, 104, 40);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button5), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image26 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox23), image26, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Rechercher "));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox23), label47, FALSE, FALSE, 0);

  afficherlesreservation = gtk_button_new ();
  gtk_widget_show (afficherlesreservation);
  gtk_fixed_put (GTK_FIXED (fixed8), afficherlesreservation, 288, 392);
  gtk_widget_set_size_request (afficherlesreservation, 120, 48);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (afficherlesreservation), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image29 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox25), image29, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox25), label49, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) retourafres, "clicked",
                    G_CALLBACK (on_retourafres_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_buttonRechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficherlesreservation, "clicked",
                    G_CALLBACK (on_afficherlesreservation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (menuafrev, menuafrev, "menuafrev");
  GLADE_HOOKUP_OBJECT (menuafrev, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (menuafrev, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (menuafrev, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (menuafrev, retourafres, "retourafres");
  GLADE_HOOKUP_OBJECT (menuafrev, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (menuafrev, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (menuafrev, image27, "image27");
  GLADE_HOOKUP_OBJECT (menuafrev, label48, "label48");
  GLADE_HOOKUP_OBJECT (menuafrev, image28, "image28");
  GLADE_HOOKUP_OBJECT (menuafrev, button5, "button5");
  GLADE_HOOKUP_OBJECT (menuafrev, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (menuafrev, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (menuafrev, image26, "image26");
  GLADE_HOOKUP_OBJECT (menuafrev, label47, "label47");
  GLADE_HOOKUP_OBJECT (menuafrev, afficherlesreservation, "afficherlesreservation");
  GLADE_HOOKUP_OBJECT (menuafrev, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (menuafrev, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (menuafrev, image29, "image29");
  GLADE_HOOKUP_OBJECT (menuafrev, label49, "label49");

  return menuafrev;
}

