/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *MenuAjout;
  GtkWidget *MenuAgents;
  GtkWidget *MenuModifier;
  GtkWidget *MenuPrincipale;
  GtkWidget *Menurechercher;
  GtkWidget *MenuResrvation;
  GtkWidget *MenuInformationPer;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
 /* MenuAjout = create_MenuAjout ();
  gtk_widget_show (MenuAjout);
  MenuAgents = create_MenuAgents ();
  gtk_widget_show (MenuAgents);
  MenuModifier = create_MenuModifier ();
  gtk_widget_show (MenuModifier);*/
  MenuPrincipale = create_MenuPrincipale ();
  gtk_widget_show (MenuPrincipale);
  /*Menurechercher = create_Menurechercher ();
  gtk_widget_show (Menurechercher);
  MenuResrvation = create_MenuResrvation ();
  gtk_widget_show (MenuResrvation);
  MenuInformationPer = create_MenuInformationPer ();
  gtk_widget_show (MenuInformationPer);*/

  gtk_main ();
  return 0;
}

